#!/bin/sh -eux

git clone https://github.com/rampantpixels/rpmalloc.git src/3rdparty/rpmalloc/rpmalloc
cd src/3rdparty/rpmalloc/rpmalloc
git checkout e8b3be9
cd -

ub_compile \
	-DWANT_QT6=ON \
	-DWANT_CARLA=OFF
