#!/bin/sh -eux

rm -f CMakeLists.txt

ub_compile \
    -Dasserts=false \
    -Dchecks=false \
    -Dmodular_tests=disabled \
    -Ddbus_user=messagebus \
    -Dinotify=enabled \
    -Druntime_dir=/run \
    -Dsystem_pid_file=/run/dbus/pid \
    -Dsystem_socket=/run/dbus/system_bus_socket \
    -Dsystemd_system_unitdir=/usr/lib/systemd/system \
    -Dsystemd=enabled \
    -Dtools=true \
    -Duser_session=true \
    -Dverbose_mode=true \
    -Dx11_autolaunch=enabled
