#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/boot
cd build/x86_64
# 8.00-tól egy bináris van: mt86plus
# https://github.com/memtest86plus/memtest86plus/commit/71d061a4c7cd22fe882bb025b3a061745d952d4c
install -m 644 mt86plus "$UB_INSTALLDIR"/boot/
