#!/bin/sh -eux

# patchelf for bootjdk
find bootjdk/bin -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
find bootjdk/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;

unset JAVA_HOME

_CFLAGS=" -O2 -Wno-error"
_CXXFLAGS=" -O2 -Wno-error"
_LDFLAGS=" -Wl,--as-needed"

bash configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sharedstatedir=/var \
    --with-boot-jdk=./bootjdk \
    --with-stdc++lib=dynamic \
    --with-extra-cflags="${_CFLAGS}" \
    --with-extra-cxxflags="${_CXXFLAGS}" \
    --with-extra-ldflags="${_LDFLAGS}" \
    --with-giflib=system \
    --with-zlib=system \
    --enable-unlimited-crypto

make
