#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/lib/java

ub_install

find ${UB_INSTALLDIR}/usr -iname '*.jar' -exec chmod ugo+r {} \;
chmod ugo+r ${UB_INSTALLDIR}/usr/lib/java/lib/ct.sym

find ${UB_INSTALLDIR}/usr -iname '*.diz' -delete
find ${UB_INSTALLDIR}/usr -iname '*.debuginfo' -delete
find ${UB_INSTALLDIR}/usr -iname '*.so' -exec chmod +x {} \;
