#!/bin/sh -eux

cd flit_core
pythonver=$(python3 -V | sed 's/Python /python/' | sed s/\.\..$//)
sitedir=${UB_INSTALLDIR}/usr/lib/${pythonver}/site-packages
mkdir -p $sitedir
python3 bootstrap_install.py --installdir $sitedir dist/flit_core-*.whl
