#!/bin/sh -eux

# ha még nincs menu-cache
export BOOTSTRAP=0

if [ $BOOTSTRAP = "1" ]; then

ub_compile \
	--with-extra-only
exit 0

else
ub_compile \
	--enable-udisks \
	--with-gnu-ld \
	--with-gtk=3

exit 0
fi
