#!/bin/sh -eux

ub_compile \
    --enable-dynamic \
    --enable-syslog \
    --enable-ipv6 \
    --enable-local \
    --enable-crypt \
    --enable-spasswd \
    --enable-modules \
    --enable-backends \
    --disable-wt \
    --enable-overlays=mod \
    --with-cyrus-sasl \
    --with-threads
