#!/bin/sh -eux

export CFLAGS+="-O2 -fPIC -std=c11 -w -D_GNU_SOURCE -D_DEFAULT_SOURCE"

./configure \
    --prefix=/usr \
	--enable-libxml2-backend	\
	--disable-abyss-server		\
	--disable-wininet-client	\
	--disable-libwww-client
make
