#!/bin/sh -eux

find . -name 'CMakeLists.txt' -delete

chmod +x lib/common/*.py

NOCONFIGURE=1 ./autogen.sh
export LIBPOSTFIX=/
export PERL=perl5
./configure \
    --prefix=/usr \
	--enable-ocaml=no \
	--enable-perl=yes
ub_make
