#!/bin/sh -eux

find . -name 'CMakeLists.txt' -delete

chmod +x lib/common/*.py

NOCONFIGURE=1 ./autogen.sh
export LIBPOSTFIX=/
ub_configure \
	--enable-ocaml=no \
	--enable-perl=no \
	--enable-tk=no \
	--enable-tcl=no \
	--enable-ruby=no \
	--enable-lua=no \
	--enable-python=no

cd lib
ub_compile

cd ../cmd/gvedit
ub_compile
