#!/bin/sh -eux

ub_install

ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/system-login
ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/system-local-login

# unix_chkpwd needs setuid bit
chmod 4755 "$UB_INSTALLDIR"/usr/sbin/unix_chkpwd
