diff -Naur a/Makefile b/Makefile
--- a/Makefile	2026-06-30 17:26:32.000000000 +0200
+++ b/Makefile	2026-07-06 00:19:26.023725444 +0200
@@ -36,7 +36,7 @@
 LMDB_VERSION	= 1.0.0
 SOFULL	= $(SOEXT).$(VEREXT)
 
-prefix	= /usr/local
+prefix	= /usr
 exec_prefix = $(prefix)
 bindir = $(exec_prefix)/bin
 libdir = $(exec_prefix)/lib
