#!/bin/sh -eux

ub_configure \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--libdir=/usr/lib \
	--with-group-name-max-length=32 \
	--with-gnu-ld \
	--disable-logind \
	--disable-man \
	--without-audit \
	--without-libbsd \
	--without-libpam \
	--without-selinux

make CFLAGS=-fPIC
